#numpy array and list

In [20]:
print("mahir")

mahir


In [21]:
import numpy as np

In [22]:
arr1=np.array([1,2,3,4,5,6])

In [23]:
print(arr1)

[1 2 3 4 5 6]


In [24]:
arr2=np.array([[1,2,3,4],[1,4,6,7]])

In [25]:
arr2

array([[1, 2, 3, 4],
       [1, 4, 6, 7]])

list vs numpy

In [26]:
arrlist=[1,2,3,4,5,6,7,8,9,10]

different behaviour

In [27]:
print(arrlist*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
print(arr1*2)

[ 2  4  6  8 10 12]


In [29]:
np_array=np.arange(1000)*3

In [30]:
zero=np.zeros((3,4))

In [31]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((2,3))


array([[0.61255319, 0.45533028, 0.95410859],
       [0.41985059, 0.81938923, 0.9285599 ]])

###vector,matrics and tensor

In [33]:
vector = np.array([1,2,3])
matrix=np.array([[1,2,3],[45,554,54]])
tensor=np.array([[[1,2],[2,3]],
                 [[1,3],[8,3]]])
print(vector)
print(matrix)
print(tensor)


[1 2 3]
[[  1   2   3]
 [ 45 554  54]]
[[[1 2]
  [2 3]]

 [[1 3]
  [8 3]]]


### array properties

In [34]:
arr1

array([1, 2, 3, 4, 5, 6])

In [38]:
print(arr2.ndim,arr2.size,arr2.shape,arr2.dtype)

2 8 (2, 4) int64


In [39]:
arr1.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])