In [5]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([[0,1,2,3,4,5]],np.int64)

In [11]:
arr[0,1]

np.int64(1)

In [10]:
arr.shape

(1, 6)

In [12]:
arr[0]+2

array([2, 3, 4, 5, 6, 7])

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(100)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
rng.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [20]:
emp=np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.11261027e-306,
        1.02360731e-306, 1.11261027e-306, 1.02360731e-306]])

In [22]:
for i in emp.flat:
    print(i)

6.230420704259778e-307
4.672967463650385e-307
1.6912109553714024e-306
2.3364684541548958e-307
1.4241355463760196e-306
1.7801908217136375e-306
1.3795974001653568e-306
6.230573489718155e-307
1.0236093493850094e-306
1.6912041649019805e-306
1.7802234158176518e-306
6.230580280829982e-307
1.0681142218209482e-306
9.45699680004398e-308
1.1125885371444853e-306
1.112615019651964e-306
1.4241083850164095e-306
7.565977700541159e-307
6.230597256278243e-307
1.4241953022955674e-306
1.1126102663813959e-306
1.0236073120929126e-306
1.1126102664124752e-306
1.0236073120929126e-306


In [23]:
emp.argmax()

np.int64(10)

In [24]:
emp.argsort()

array([[3, 1, 0, 4, 2, 5],
       [1, 5, 2, 0, 3, 4],
       [1, 5, 0, 2, 3, 4],
       [0, 3, 5, 2, 4, 1]])

In [25]:
emp.argmax(axis=0)

array([1, 3, 0, 1, 1, 0])

In [26]:
emp.sum()

np.float64(2.522855677958383e-305)

In [ ]:
print("mahir")

In [8]:
n=pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
n

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35