### operation

In [5]:
import numpy as np

In [6]:
arr=np.arange(12)
print(arr[2:7])
print(arr[2:10:2])



[2 3 4 5 6]
[2 4 6 8]


In [7]:
arr2=arr.reshape((3,4))
print(arr2)
print(arr2[1,2])
print(arr2[2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[ 8  9 10 11]
